const alumniData=[
  {"name": "Aman Dhananjay", "branch": "IT", "linkedin": "https://www.linkedin.com/in/aman-dhananjay-8143a723a/"},
  {"name": "Anjali Rege", "branch": "Mechanical", "linkedin": "https://www.linkedin.com/in/anjali-rege-601a53253/"},
  {"name": "Archisha De", "branch": "Mechanical", "linkedin": "https://www.linkedin.com/in/archisha-de-8aa5a9230/"},
  {"name": "Ekant Sahu", "branch": "Electrical", "linkedin": "https://www.linkedin.com/in/ekant-sahu"},
  {"name": "Piyush Kumar", "branch": "Mechanical", "linkedin": "https://www.linkedin.com/in/piyush-kumar-796513297"},
  {"name": "Harsh Jangir", "branch": "Electrical", "linkedin": "https://www.linkedin.com/in/harsh003"},
  {"name": "Ramatemki Keerthi", "branch": "ECE", "linkedin": "https://www.linkedin.com/in/keerthi-ramatenki-608649229"},
  {"name": "Ayush Damor", "branch": "Electrical", "linkedin": "https://www.linkedin.com/in/ayush-damor-95458a264"},
  {"name": "Chanchal Thakur", "branch": "ECE", "linkedin": "https://www.linkedin.com/in/chanchal-thakur01"},
  {"name": "Aman Verma", "branch": "ECE", "linkedin": "https://www.linkedin.com/in/aman-verma-894486232"},
  {"name": "Chitwan Raj", "branch": "", "linkedin": "https://www.linkedin.com/in/chitwanraj"},
  {"name": "Rashmi Prakash", "branch": "Electrical", "linkedin": "https://www.linkedin.com/in/rpsatapathy04/"},
  {"name": "Chandrika Geddada", "branch": "ECE", "linkedin": "https://www.linkedin.com/in/prathamgandhi1308"},
  {"name": "Pratham Gandhi", "branch": "CSE", "linkedin": ""},
  {"name": "Rashmiprakash Satapathy", "branch": "Electrical", "linkedin": "https://www.linkedin.com/in/rpsatapathy04/"},
  {"name": "Aditya Ray", "branch": "", "linkedin": ""},
  {"name": "S. Sathvik", "branch": "ECE", "linkedin": "https://www.linkedin.com/in/sathvik-s-496628225/"},
  {"name": "Avi Yadav", "branch": "Mining", "linkedin": "https://www.linkedin.com/in/avi-yadav-505749211/"},
  {"name": "Ayush Hardaha", "branch": "Mechanical", "linkedin": "https://www.linkedin.com/in/ayush-hardaha-55792a211/"},
  {"name": "Deepshikha Sharma", "branch": "ECE", "linkedin": "https://www.linkedin.com/in/deepshikha-sharma1603/"},
  {"name": "Gautam Raghwani", "branch": "Mining", "linkedin": "https://www.linkedin.com/in/gautam-raghwani/"},
  {"name": "Prakriti Khilnani", "branch": "Mechanical", "linkedin": "https://www.linkedin.com/in/prakritikhilnani/"},
  {"name": "Pramil Kesarwani", "branch": "ECE", "linkedin": ""},
  {"name": "Jayant Patel", "branch": "Mechanical", "linkedin": "https://www.linkedin.com/in/jayant-patel-76b596206"},
  {"name": "Vineeth_BE", "branch": "ECE", "linkedin": "https://www.linkedin.com/in/vineethxyz09"},
  {"name": "Utkarsh Maurya", "branch": "ECE", "linkedin": "https://www.linkedin.com/in/utkarsh-maurya-83a344205/"},
  {"name": "Ujjwal Likhar", "branch": "", "linkedin": "https://www.linkedin.com/in/ujjwallikhar/"},
  {"name": "Jay Prakash", "branch": "Electrical", "linkedin": "https://www.linkedin.com/in/jay-prakash-002"},
  {"name": "Sahas Bansod", "branch": "Mechanical", "linkedin": "https://www.linkedin.com/in/sahas-bansod-a32a32232"},
  {"name": "Vahini Gannavarapu", "branch": "Mechanical", "linkedin": "https://www.linkedin.com/in/vahini-gannavarapu-a7964a194"},
  {"name": "Shashank Raghupatro", "branch": "Metallurgy", "linkedin": "https://www.linkedin.com/in/shashank-raghupatro"},
  {"name": "D Gopal Krishna", "branch": "Mechanical", "linkedin": "https://www.linkedin.com/in/d-gopal-krishna/"},
  {"name": "Gopal Agrawal", "branch": "Electrical", "linkedin": "https://www.linkedin.com/in/gopalagrawal4"},
  {"name": "Vikash Koshle", "branch": "Electrical", "linkedin": "https://www.linkedin.com/in/vikash-koshle-27b35a153"},
  {"name": "Anmol Agarwal", "branch": "Electrical", "linkedin": "https://www.linkedin.com/in/anmolagrawal20"},
  {"name": "Pratik Singh Thakur", "branch": "Electrical", "linkedin": "https://www.linkedin.com/in/pratik-singh-thakur-a4b0b71a5"},
  {"name": "Jyotirmoy Ghosh", "branch": "Mechanical", "linkedin": "https://www.linkedin.com/in/jyotirmoy-ghosh877"},
  {"name": "Aman Priyansh John", "branch": "Mechanical", "linkedin": "https://www.linkedin.com/in/aman-priyansh-john-276508190"},
  {"name": "Ansh Srivastava", "branch": "Mining", "linkedin": "https://www.linkedin.com/in/anshsrtv"},
  {"name": "Aayush Paikra", "branch": "Electrical", "linkedin": "https://www.linkedin.com/in/aayush-paikra-757364196"},
  {"name": "Aditya Chourasia", "branch": "ECE", "linkedin": "https://www.linkedin.com/in/aditya-chourasia1080"},
  {"name": "Akansha Agrawal", "branch": "Electrical", "linkedin": "https://www.linkedin.com/in/akansha-agrawal-b0217118a"},
  {"name": "Aman Swarnkar", "branch": "Chemical", "linkedin": "https://www.linkedin.com/in/aman-swarnkar"},
  {"name": "Anukriti Das", "branch": "Mechanical", "linkedin": "https://www.linkedin.com/in/anukruti-das-0875bb188"},
  {"name": "Anurag Jaiswal", "branch": "Mining", "linkedin": "https://www.linkedin.com/in/anurag-jaiswal-6b1234211"},
  {"name": "Ashutosh Tiwari", "branch": "Electrical", "linkedin": "https://www.linkedin.com/in/ashutosh-tiwari-12178b191"},
  {"name": "Dharmveer Sharma", "branch": "ECE", "linkedin": "https://www.linkedin.com/in/dharm-veer-sharma"},
  {"name": "Manya Mishra", "branch": "Metallurgy", "linkedin": "https://www.linkedin.com/in/manya-mishra-71b0a2187"},
  {"name": "Ritish Kumar Tiwari", "branch": "Electrical", "linkedin": "https://www.linkedin.com/in/ritish-kumar-tiwari-144763108"},
  {"name": "Rohan Agrawal", "branch": "Mechanical", "linkedin": "https://www.linkedin.com/in/rohan-agrawal-59321a186"},
  {"name": "Shreyas Royzada", "branch": "Mechanical", "linkedin": "https://www.linkedin.com/in/shreyash-royzada-83b44a118"},
  {"name": "Soumya Sharma", "branch": "Electrical", "linkedin": "https://www.linkedin.com/in/sharma-soumya"},
  {"name": "Yogesh Markandey", "branch": "Metallurgy", "linkedin": "https://www.linkedin.com/in/yogehmarkandey6654063-0bb0621b4"},
  {"name": "Vivek Nag", "branch": "Civil", "linkedin": "https://www.linkedin.com/in/vivek-nag-5ab071190"},
  {"name": "Christi S Mathai", "branch": "Mining", "linkedin": "https://www.linkedin.com/in/christi-s-mathai-3b04b4169"},
  {"name": "Ishneet Bhatia", "branch": "Metallurgy", "linkedin": "https://www.linkedin.com/in/ishneet-bhatia"},
  {"name": "Kanishka Gabel", "branch": "Mechanical", "linkedin": "https://www.linkedin.com/in/kanishka-gabel"},
  {"name": "Mahendra Gavel", "branch": "Electrical", "linkedin": "https://www.linkedin.com/in/mahendra-gavel"},
  {"name": "Rishi Gupta", "branch": "", "linkedin": "https://www.linkedin.com/in/rishigupta046"},
  {"name": "Shreyash Ganvir", "branch": "Electrical", "linkedin": "https://www.linkedin.com/in/shreyash-ganvir-a557a6152"},
  {"name": "Simran Bajaj", "branch": "ECE", "linkedin": "https://www.linkedin.com/in/simran-bajaj-891582166"},
  {"name": "Sudhansh Chopda", "branch": "Biomed", "linkedin": "https://www.linkedin.com/in/sudhansh-chopda"},
  {"name": "Tanay Naik", "branch": "Biomed", "linkedin": "https://www.linkedin.com/in/tanay-naik-8b991a169"},
  {"name": "Uttara Khatik", "branch": "ECE", "linkedin": "https://www.linkedin.com/in/uttara-khatik-0857ab163"},
  {"name": "Yashwant Kothale", "branch": "Mechanical", "linkedin": "https://www.linkedin.com/in/yashwant-kothale-24b888157"},
  {"name": "Devesh Patel", "branch": "ECE", "linkedin": "https://www.linkedin.com/in/devesh-patel-a0898a164"},
  {"name": "Manoj Pisini", "branch": "BioTech", "linkedin": "https://www.linkedin.com/in/manoj-pisini/"},
  {"name": "Bharat Dadhich", "branch": "Biotech", "linkedin": "https://www.linkedin.com/in/bharat-dadhich-20b893155"},
  {"name": "Sri Sai Suhas Khandavalli", "branch": "Electrical", "linkedin": "https://www.linkedin.com/in/srisaisuhas"},
  {"name": "Muskan Jain", "branch": "Metallurgy", "linkedin": "https://www.linkedin.com/in/muskan-jain-71a1b3140"},
  {"name": "Shruti Pandey", "branch": "ECE", "linkedin": "https://www.linkedin.com/in/shruti-pandey-171b52150/"},
  {"name": "Kunal Sinha", "branch": "Metallurgy", "linkedin": "https://www.linkedin.com/in/kunal2811/"},
  {"name": "Kushal Gupta", "branch": "Mechanical", "linkedin": "https://www.linkedin.com/in/kushal-gupta-7a0972130/"},
  {"name": "Yashasva Paras", "branch": "Electrical", "linkedin": "https://www.linkedin.com/in/yashasva-paras/"},
  {"name": "Upasana Mishra", "branch": "ETE", "linkedin": "https://www.linkedin.com/in/upasana-mishra/"},
  {"name": "Prateek Gautam", "branch": "Mining", "linkedin": "https://www.linkedin.com/in/prateek-gautam-84757816a/"},
  {"name": "K Pooja", "branch": "IT", "linkedin": ""},
  {"name": "Prabal Dev", "branch": "IT", "linkedin": "https://www.linkedin.com/in/prabal-dev?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app"},
  {"name": "Nischay Soni", "branch": "Mechanical", "linkedin": ""},
  {"name": "Ayush Mishra", "branch": "Electrical", "linkedin": ""},
  {"name": "Kartikay Shanker", "branch": "Electrical", "linkedin": "https://www.linkedin.com/in/prabal-dev?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app"},
  {"name": "Aman Ranka", "branch": "Electrical", "linkedin": "https://www.linkedin.com/in/aman-ranka-462914200"},
  {"name": "Rohit Bajaj", "branch": "Electrical", "linkedin": "https://www.linkedin.com/in/rohit-bajaj-l14"},
  {"name": "Milan Chandrakar", "branch": "Mechanical", "linkedin": "https://www.linkedin.com/in/milan1996"},
  {"name": "Pranay Sahu", "branch": "Mechanical", "linkedin": "https://www.linkedin.com/in/pranaysahu96"},
  {"name": "Nischay Soni", "branch": "Mechanical", "linkedin": "https://www.linkedin.com/in/nischay-soni-a28029129/"},
  {"name": "Shubham Gupta", "branch": "Mechanical", "linkedin": "https://www.linkedin.com/in/shubhamgupta45/"},
  {"name": "Rohit Agarwal", "branch": "IT", "linkedin": "Rohit Agarwal | LinkedIn"},
  {"name": "Ronak Pani", "branch": "Mechanical", "linkedin": "https://www.linkedin.com/in/ronak-pani-69550872"},
  {"name": "Rao Yashovardhan Singh", "branch": "Mechanical", "linkedin": "https://www.linkedin.com/in/rao-yashovardhan-singh-226889141"},
  {"name": "G Naveen Kumar", "branch": "Electrical", "linkedin": "https://www.linkedin.com/in/g-naveen-kumar-ab5a70141?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app"},
  {"name": "Anshu K. Banjare", "branch": "Mechanical", "linkedin": ""},
  {"name": "Ajay Kumar Saini", "branch": "Electrical", "linkedin": "https://www.linkedin.com/in/ajay-kumar-saini-389145129"},
  {"name": "Nishtha Bhimte", "branch": "ETE", "linkedin": "https://www.linkedin.com/in/nishtha-bhimte/"},
  {"name": "Tejas Kanikdaley", "branch": "ETE", "linkedin": "https://www.linkedin.com/in/tejaskanikdaley/"},
  {"name": "Vishal Gupta", "branch": "ETE", "linkedin": "https://www.linkedin.com/in/vishal9596/"},
  {"name": "Ankit Pawar", "branch": "Mechanical", "linkedin": "https://www.linkedin.com/in/ankitpawar7/"},
  {"name": "Pankaj Yadav", "branch": "Elex", "linkedin": "https://www.linkedin.com/in/pankaj-yadav-0b546074/"}
];
export default alumniData;